### ISSUE TITLE
@supports rules causes Error: Could not parse CSS stylesheet

### ISSUE THREAD

**Issue by foolip** [jsdom/jsdom#2026]
### Basic info:

- **Node.js version:** 8.5.0
- **jsdom version:** 11.3.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

new JSDOM(`<style>
  @supports (text-decoration-style: solid) {
    ul.toc a:hover, ul.toc a:focus  {
    }
  }
</style>`)
```

This results in this console output:
```
Error: Could not parse CSS stylesheet
    at exports.evaluateStylesheet (/redacted/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:18:21)
    at HTMLStyleElementImpl._attach (/redacted/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:23:5)
    at HTMLHeadElementImpl._attach (/redacted/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:281:15)
    at HTMLHeadElementImpl._attach (/redacted/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:90:11)
    at HTMLHtmlElementImpl._attach (/redacted/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:281:15)
    at HTMLHtmlElementImpl._attach (/redacted/node_modules/jsdom/lib/jsdom/living/nodes/Element-impl.js:90:11)
    at DocumentImpl.insertBefore (/redacted/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:221:22)
    at DocumentImpl.appendChild (/redacted/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:319:17)
    at DocumentImpl.appendChild (/redacted/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:394:18)
    at setChild (/redacted/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:230:18) 
  @supports (text-decoration-style: solid) {
    ul.toc a:hover, ul.toc a:focus  {
    }
  }
```

### How does similar code behave in browsers?

No console error or warning in Chrome:
https://wicg.github.io/hsts-priming/

Source:
https://github.com/WICG/hsts-priming/blob/bb84ed97793799ccc50eb36eba1d1e95722f9eb2/index.html#L856

**Comment by Zirro** [comment]
jsdom is currently using the [CSSOM](https://github.com/NV/CSSOM) package for parsing CSS. It doesn't include support for `@supports`-rules, and unfortunately no longer seems to be in active development.

I have started working on an up-to-date and standards-compliant replacement intended for use in jsdom - [css-object-model](https://github.com/Zirro/css-object-model) - but a lot of work remains before it is ready to replace the current CSSOM/CSSStyleDeclaration-dependencies in jsdom.

**Comment by domenic** [comment]
You can in the meantime suppress these logs by using the [virtual console](https://github.com/tmpvar/jsdom#virtual-consoles) to listen for `"jsdomError"` events and choose not to log them. There is even an `omitJSDOMErrors` option to do this for you, although that will suppress all error logging (e.g. uncaught runtime exception), not just CSS ones.

**Comment by foolip** [comment]
Thanks @domenic! For now I've worked around the issue with a blocklist of repos to ignore (most of them) but I'll use omitJSDOMErrors if this happens on something I don't want to ignore.

**Comment by PeterShershov** [comment]
Hey, any progress with this? 
I'm trying to use CSS.supports() with Jest and it's not implemented yet apparently.

**Comment by devrelm** [comment]
For what it's worth, there is an open PR at CSSOM here: /NV/CSSOM#94

It's currently waiting on tests being written, which I'm hoping to do tonight.

**Comment by devrelm** [comment]
For what it's worth, there is an open PR at CSSOM here: NV/CSSOM#94

It's currently waiting on tests being written, which I'm hoping to do tonight.

**Comment by devrelm** [comment]
This was fixed with NV/CSSOM#94 & NV/CSSOM#96, and available in CSSOM v0.3.3. It looks like `jsdom` is just looking for `>= 0.3.2 < 0.4.0`, so it should be available to end users by updating that sub-dependency.

Upgrading the sub-dependency might be easier said than done for some users since there's no easy way to do it in `yarn` (or possibly in `npm` either.)

I did it with a little manual editing, like so:
* `yarn add cssom`
* find the `cssom` dependencies in my `yarn.lock`. It should look something like this:
  ```
  "cssom@>= 0.3.2 < 0.4.0"
    version "0.3.2"
    resolved "https://registry.yarnpkg.com/cssom/-/cssom-0.3.2.tgz#b8036170c79f07a90ff2f16e22284027a243848b"

  cssom@^0.3.3"
    version "0.3.3"
    resolved "https://registry.yarnpkg.com/cssom/-/cssom-0.3.3.tgz#7b344769915759c2c9e3eb8c26f7fd533dbea252"
  ```
* replace the `version "0.3.2"` and following line with its `version "0.3.3"` counterparts. You should be left with a diff like so:
  ```
   "cssom@>= 0.3.2 < 0.4.0"
  -  version "0.3.2"
  -  resolved "https://registry.yarnpkg.com/cssom/-/cssom-0.3.2.tgz#b8036170c79f07a90ff2f16e22284027a243848b"
  +  version "0.3.3"
  +  resolved "https://registry.yarnpkg.com/cssom/-/cssom-0.3.3.tgz#7b344769915759c2c9e3eb8c26f7fd533dbea252"
```
* revert your `package.json` to remove the direct dependency on `cssom` (if you don't need it)
* run `yarn` to double-check that everything still works and to remove `cssom@0.3.2`.

**Comment by adyz** [comment]
@devrelm  -- just running `npm install --save-dev cssom` worked for me!

Thanks a ton!

**Comment by PeterShershov** [comment]
Great! Thanks!

**Comment by mikelovesrobots** [comment]
If you're using `yarn`, you can override the resolved version in your `package.json`:

```
  "resolutions": {
    "cssom": "0.3.3"
  }
```

Hat tip: @nsimonson who pointed out the resolutions directive to me.

**Comment by chadwtkns** [comment]
Hi so Im running into this issue as well with my error being 

```bash
    TypeError: CSS.supports is not a function

      1 | import {html, render} from 'lit-html'
      2 |
    > 3 | import '@vaadin/vaadin-grid';
        | ^
      4 | import '@vaadin/vaadin-button';
      5 | import '@vaadin/vaadin-text-field';
      6 | import '@vaadin/vaadin-date-picker';
```

but Im having a hard time gathering what the resolution is from this ticket?

**Comment by danbeam** [comment]
I haven't tried it, but it seems like `@supports` is now implemented in CSSOM as per https://github.com/jsdom/jsdom/issues/2026#issuecomment-401843831.

perhaps worth separating (or repurposing) for the [`CSS.supports()`](https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports) API specifically?

@devrelm @NV does it makes sense/are there plans to implement `CSS.supports()` in [CSSOM](https://github.com/NV/CSSOM) or does that "Unmaintained! ⚠️ " mean no?

**Comment by yagudaev** [comment]
This issue can be safely closed now. It works fine with `26.1.0`.

See: https://replit.com/@michael352/JsdomExplorer#index.js

**Comment by jdufresne** [comment]
> perhaps worth separating (or repurposing) for the [`CSS.supports()`](https://developer.mozilla.org/en-US/docs/Web/API/CSS/supports) API specifically?

I opened issue https://github.com/jsdom/jsdom/issues/3991 for this purpose.
