### ISSUE TITLE
[version 20.0 regression] TypeError: url.path.join is not a function

### ISSUE THREAD

**Issue by babatakao** [jsdom/jsdom#3431]
### Basic info:

- **Node.js version:** 16.13.0
- **jsdom version:** 20.0.0

An error "TypeError: url.path.join is not a function" is caused when `location.pathname` is referenced.

### Minimal reproduction case

```js
const jsdom = require('jsdom');                                                                                                                                                                                                                   
const { JSDOM } = jsdom;                                                        
const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);                     
console.log(dom.window.location.pathname);
```

the result:

```
/tmp/url-test/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:141
    return "/" + url.path.join("/");
                          ^

TypeError: url.path.join is not a function
    at LocationImpl.get pathname [as pathname] (/tmp/url-test/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:141:27)
    at Location.get pathname [as pathname] (/tmp/url-test/node_modules/jsdom/lib/jsdom/living/generated/Location.js:255:35)
    at Object.<anonymous> (/tmp/url-test/test.js:4:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

In the case `url.path` is a string `"blank"`, not an array.

### How does similar code behave in browsers?

```js
console.log(location.pathname);
```

### Note

I suspect this issue is caused by whatwg-url@11.0.0 breaking change. [release note](https://github.com/jsdom/whatwg-url/releases/tag/v11.0.0) says

> Changed the URL record type's path from always being an array of strings, to being either a single string or an array of strings.

**Comment by nrandell** [comment]
I've just run into this. If I add a resolutions entry to my package.json, it all works ok

```
  "resolutions": {
    "whatwg-url": "10"
  }
```

**Comment by sergey-v9** [comment]
faced same issue after an upgrade to 20.0

as a workaround i've replaced this part:
```
  const dom = new JSDOM('', {
    runScripts: 'outside-only',
  });
```
with:
```
  const dom = new JSDOM('', {
    url: 'https://example.com/', // workaround for https://github.com/jsdom/jsdom/issues/3431
    runScripts: 'outside-only',
  });
```

luckily, this is the only one place in a code where the `JSDOM` constructor called, in my case

**Comment by cmloegcmluin** [comment]
In my case, both the "whatwg-url" resolution suggested by @nrandell _and_ the dummy url option suggested by @sergey-v9  were required to solve the problem. Thank you both.

**Comment by domenic** [comment]
Thank you all for detecting this, and particularly the clear, issue-template-following bug report. It appears there's no web platform test coverage for `location.pathname` on `about:blank` pages (which is the default URL of a `JSDOM` instance created without supplying a `url` option).

I will post a fix and do a release shortly.
