### ISSUE TITLE
Implement CSSStyleSheet replace() and replaceSync()

### ISSUE THREAD

**Issue by vinsonchuong** [jsdom/jsdom#3766]
### Basic info:

- **Node.js version:** 22.6.0
- **jsdom version:** 24.1.1

It looks like the current implementation of `CSSStyleSheet` is missing a couple of methods that I am using to power automated tests for a web components library.

### Minimal reproduction case

```js
import {JSDOM} from 'jsdom'

const {window} = new JSOM('<!doctype html>')

const stylesheet = new window.CSSStyleSheet()
await stylesheet.replace('body { color: red; }')
```

### How does similar code behave in browsers?

I expect the methods `replace()` and `replaceSync()` to exist and behave as documented (https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet)

**Comment by benjgil** [comment]
I'm now getting a `replaceSync is not a function` error when trying to test a react component that has a stencil component as a deep-ish dependency. Not sure why this suddenly started happening now, but it sounds like a direct result of replaceSync not being implemented in jsdom...

Error:
``` 
TypeError: sheet.replaceSync is not a function

    > 76 |       const renderResult = render(<Chat />);
         |                                  ^
      77 |       container = renderResult.container;
      78 |     });
      79 |
```

The code inside the stencil library that's causing the error:
```
function createShadowRoot(cmpMeta) {
  const shadowRoot = BUILD8.shadowDelegatesFocus ? this.attachShadow({
    mode: "open",
    delegatesFocus: !!(cmpMeta.$flags$ & 16 /* shadowDelegatesFocus */)
  }) : this.attachShadow({ mode: "open" });
  const sheet = new CSSStyleSheet();
  sheet.replaceSync(globalStyles);
  shadowRoot.adoptedStyleSheets.push(sheet);
}
```

If jest-dom cant work with relatively mainstream webcomponent libraries then this is a pretty big hole...

**Comment by maxrrv** [comment]
@benjgil Have you updated to a version of your component library that has a newer @stencil/core version installed? If so, that's why the error appears. It happened to us too after updating @stencil/core from 4.19 to >=4.27. I'm not sure if that's the first version where this error occurs, but it is the version where we spotted that error. 

You can polyfill CSSStyleSheet for the time being yourself in your setupTests file: 
```
import '@testing-library/jest-dom';

// Mock adoptedStyleSheets property on Document and ShadowRoot
Object.defineProperty(Document.prototype, 'adoptedStyleSheets', {
  get() {
    return this._adoptedStyleSheets || [];
  },
  set(styleSheets) {
    this._adoptedStyleSheets = styleSheets;
  },
  configurable: true,
});

Object.defineProperty(ShadowRoot.prototype, 'adoptedStyleSheets', {
  get() {
    return this._adoptedStyleSheets || [];
  },
  set(styleSheets) {
    this._adoptedStyleSheets = styleSheets;
  },
  configurable: true,
});

// Mock CSSStyleSheet constructor
global.CSSStyleSheet = class CSSStyleSheet {
  cssRules: any[] = [];
  rules: any[] = [];
  ownerRule: any = null;
  ownerNode: any = null;
  parentStyleSheet: any = null;
  href: string | null = null;
  title = '';
  media: any = {
    mediaText: '',
    length: 0,
    item: () => null,
    deleteMedium: () => {},
    appendMedium: () => {},
  };
  disabled = false;
  type = 'text/css';

  constructor() {}

  replaceSync() {
    return;
  }

  replace() {
    return Promise.resolve(this);
  }

  insertRule() {
    return 0;
  }

  deleteRule() {}

  addRule() {
    return -1;
  }

  removeRule() {}
} as any;

```

and then link your setupTests.js file in your jest.config.js or vite.config.js

Vite:
```
{
  test: {
    setupFiles: 'path/to/your/setupTests.js',
  }
}
```

Jest:
```
{
  setupFilesAfterEnv: 'path/to/your/setupTests.js',
}
```
I hope that helps you for the time being :)

**Comment by benjgil** [comment]
thanks @maxrrv - that is very helpful and fixes the issues we were seeing

Re the Stencil version, we're using an internal design library that brings in the stencil version, so we dont have control over that. I can say that we havent changed the version of that library we're using, but it's very possible that some recent resetting of the package-lock file meant newer versions of the Stencil deep dep were updated to in the background.

Either way, hopefully someone finds and fixes this issue, another step towards maturity of custom elements... :)
